#ifndef _INCLUDE_GUARD_CSS_ERROR_H_
#define _INCLUDE_GUARD_CSS_ERROR_H_

enum _tagCSS_ERROR;
typedef enum _tagCSS_ERROR CSS_ERROR;
enum _tagCSS_ERROR
{
	CSS_ERROR_SUCCESS,
	CSS_ERROR_NULLPTR,
	CSS_ERROR_TOO_BIG,
	CSS_ERROR_TOO_SMALL,
};

#endif
